ERROR - 2021-08-31 14:19:29 --> Error connecting to the database: No such file or directory
CRITICAL - 2021-08-31 14:19:29 --> Unable to connect to the database.
Main connection [MySQLi]: No such file or directory
#0 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->initialize()
#1 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 /var/www/html/vendor/codeigniter4/framework/system/Model.php(197): CodeIgniter\Database\BaseBuilder->get()
#3 /var/www/html/vendor/codeigniter4/framework/system/BaseModel.php(603): CodeIgniter\Model->doFindAll(0, 0)
#4 /var/www/html/app/Controllers/Api/V1/Users.php(20): CodeIgniter\BaseModel->findAll()
#5 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): App\Controllers\Api\V1\Users->index()
#6 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Users))
#7 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2021-08-31 14:19:44 --> Error connecting to the database: No such file or directory
ERROR - 2021-08-31 14:20:57 --> Error connecting to the database: Access denied for user '****'@'172.28.0.4' (using ****: YES)
ERROR - 2021-08-31 14:21:14 --> Error connecting to the database: Access denied for user '****'@'172.28.0.4' (using ****: YES)
ERROR - 2021-08-31 14:39:27 --> Table 'codeigniter_db.users' doesn't exist
CRITICAL - 2021-08-31 14:39:27 --> Table 'codeigniter_db.users' doesn't exist
#0 /var/www/html/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(329): mysqli->query('SELECT *\nFROM `...')
#1 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /var/www/html/vendor/codeigniter4/framework/system/Model.php(197): CodeIgniter\Database\BaseBuilder->get()
#5 /var/www/html/vendor/codeigniter4/framework/system/BaseModel.php(603): CodeIgniter\Model->doFindAll(0, 0)
#6 /var/www/html/app/Controllers/Api/V1/Users.php(20): CodeIgniter\BaseModel->findAll()
#7 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): App\Controllers\Api\V1\Users->index()
#8 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Users))
#9 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2021-08-31 14:40:16 --> Error connecting to the database: Access denied for user '****'@'172.29.0.4' (using ****: YES)
CRITICAL - 2021-08-31 14:40:16 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'172.29.0.4' (using ****: YES)
#0 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->initialize()
#1 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 /var/www/html/vendor/codeigniter4/framework/system/Model.php(197): CodeIgniter\Database\BaseBuilder->get()
#3 /var/www/html/vendor/codeigniter4/framework/system/BaseModel.php(603): CodeIgniter\Model->doFindAll(0, 0)
#4 /var/www/html/app/Controllers/Api/V1/Users.php(20): CodeIgniter\BaseModel->findAll()
#5 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): App\Controllers\Api\V1\Users->index()
#6 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Users))
#7 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-08-31 14:40:16 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in /var/www/html/app/Views/errors/html/error_exception.php:99
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', '/var/www/html/a...', 99, Array)
#1 /var/www/html/app/Views/errors/html/error_exception.php(99): print_r(Object(App\Controllers\Api\V1\Users), true)
#2 /var/www/html/vendor/codeigniter4/framework/system/Debug/Exceptions.php(278): include('/var/www/html/a...')
#3 /var/www/html/vendor/codeigniter4/framework/system/Debug/Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-08-31 14:40:56 --> Error connecting to the database: Access denied for user '****'@'172.29.0.4' (using ****: YES)
CRITICAL - 2021-08-31 14:40:56 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'172.29.0.4' (using ****: YES)
#0 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->initialize()
#1 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 /var/www/html/vendor/codeigniter4/framework/system/Model.php(197): CodeIgniter\Database\BaseBuilder->get()
#3 /var/www/html/vendor/codeigniter4/framework/system/BaseModel.php(603): CodeIgniter\Model->doFindAll(0, 0)
#4 /var/www/html/app/Controllers/Api/V1/Users.php(20): CodeIgniter\BaseModel->findAll()
#5 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): App\Controllers\Api\V1\Users->index()
#6 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Users))
#7 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-08-31 14:40:56 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in /var/www/html/app/Views/errors/html/error_exception.php:99
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', '/var/www/html/a...', 99, Array)
#1 /var/www/html/app/Views/errors/html/error_exception.php(99): print_r(Object(App\Controllers\Api\V1\Users), true)
#2 /var/www/html/vendor/codeigniter4/framework/system/Debug/Exceptions.php(278): include('/var/www/html/a...')
#3 /var/www/html/vendor/codeigniter4/framework/system/Debug/Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-08-31 14:40:57 --> Error connecting to the database: Access denied for user '****'@'172.29.0.4' (using ****: YES)
CRITICAL - 2021-08-31 14:40:57 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'172.29.0.4' (using ****: YES)
#0 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->initialize()
#1 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 /var/www/html/vendor/codeigniter4/framework/system/Model.php(197): CodeIgniter\Database\BaseBuilder->get()
#3 /var/www/html/vendor/codeigniter4/framework/system/BaseModel.php(603): CodeIgniter\Model->doFindAll(0, 0)
#4 /var/www/html/app/Controllers/Api/V1/Users.php(20): CodeIgniter\BaseModel->findAll()
#5 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): App\Controllers\Api\V1\Users->index()
#6 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Users))
#7 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-08-31 14:40:57 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in /var/www/html/app/Views/errors/html/error_exception.php:99
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', '/var/www/html/a...', 99, Array)
#1 /var/www/html/app/Views/errors/html/error_exception.php(99): print_r(Object(App\Controllers\Api\V1\Users), true)
#2 /var/www/html/vendor/codeigniter4/framework/system/Debug/Exceptions.php(278): include('/var/www/html/a...')
#3 /var/www/html/vendor/codeigniter4/framework/system/Debug/Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-08-31 14:40:57 --> Error connecting to the database: Access denied for user '****'@'172.29.0.4' (using ****: YES)
CRITICAL - 2021-08-31 14:40:57 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'172.29.0.4' (using ****: YES)
#0 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->initialize()
#1 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 /var/www/html/vendor/codeigniter4/framework/system/Model.php(197): CodeIgniter\Database\BaseBuilder->get()
#3 /var/www/html/vendor/codeigniter4/framework/system/BaseModel.php(603): CodeIgniter\Model->doFindAll(0, 0)
#4 /var/www/html/app/Controllers/Api/V1/Users.php(20): CodeIgniter\BaseModel->findAll()
#5 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): App\Controllers\Api\V1\Users->index()
#6 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Users))
#7 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-08-31 14:40:57 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in /var/www/html/app/Views/errors/html/error_exception.php:99
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', '/var/www/html/a...', 99, Array)
#1 /var/www/html/app/Views/errors/html/error_exception.php(99): print_r(Object(App\Controllers\Api\V1\Users), true)
#2 /var/www/html/vendor/codeigniter4/framework/system/Debug/Exceptions.php(278): include('/var/www/html/a...')
#3 /var/www/html/vendor/codeigniter4/framework/system/Debug/Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-08-31 14:40:57 --> Error connecting to the database: Access denied for user '****'@'172.29.0.4' (using ****: YES)
CRITICAL - 2021-08-31 14:40:57 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'172.29.0.4' (using ****: YES)
#0 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->initialize()
#1 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 /var/www/html/vendor/codeigniter4/framework/system/Model.php(197): CodeIgniter\Database\BaseBuilder->get()
#3 /var/www/html/vendor/codeigniter4/framework/system/BaseModel.php(603): CodeIgniter\Model->doFindAll(0, 0)
#4 /var/www/html/app/Controllers/Api/V1/Users.php(20): CodeIgniter\BaseModel->findAll()
#5 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): App\Controllers\Api\V1\Users->index()
#6 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Users))
#7 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-08-31 14:40:57 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in /var/www/html/app/Views/errors/html/error_exception.php:99
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', '/var/www/html/a...', 99, Array)
#1 /var/www/html/app/Views/errors/html/error_exception.php(99): print_r(Object(App\Controllers\Api\V1\Users), true)
#2 /var/www/html/vendor/codeigniter4/framework/system/Debug/Exceptions.php(278): include('/var/www/html/a...')
#3 /var/www/html/vendor/codeigniter4/framework/system/Debug/Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-08-31 14:40:58 --> Error connecting to the database: Access denied for user '****'@'172.29.0.4' (using ****: YES)
CRITICAL - 2021-08-31 14:40:58 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'172.29.0.4' (using ****: YES)
#0 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->initialize()
#1 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 /var/www/html/vendor/codeigniter4/framework/system/Model.php(197): CodeIgniter\Database\BaseBuilder->get()
#3 /var/www/html/vendor/codeigniter4/framework/system/BaseModel.php(603): CodeIgniter\Model->doFindAll(0, 0)
#4 /var/www/html/app/Controllers/Api/V1/Users.php(20): CodeIgniter\BaseModel->findAll()
#5 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): App\Controllers\Api\V1\Users->index()
#6 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Users))
#7 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-08-31 14:40:58 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in /var/www/html/app/Views/errors/html/error_exception.php:99
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', '/var/www/html/a...', 99, Array)
#1 /var/www/html/app/Views/errors/html/error_exception.php(99): print_r(Object(App\Controllers\Api\V1\Users), true)
#2 /var/www/html/vendor/codeigniter4/framework/system/Debug/Exceptions.php(278): include('/var/www/html/a...')
#3 /var/www/html/vendor/codeigniter4/framework/system/Debug/Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-08-31 14:40:58 --> Error connecting to the database: Access denied for user '****'@'172.29.0.4' (using ****: YES)
CRITICAL - 2021-08-31 14:40:58 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'172.29.0.4' (using ****: YES)
#0 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->initialize()
#1 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 /var/www/html/vendor/codeigniter4/framework/system/Model.php(197): CodeIgniter\Database\BaseBuilder->get()
#3 /var/www/html/vendor/codeigniter4/framework/system/BaseModel.php(603): CodeIgniter\Model->doFindAll(0, 0)
#4 /var/www/html/app/Controllers/Api/V1/Users.php(20): CodeIgniter\BaseModel->findAll()
#5 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): App\Controllers\Api\V1\Users->index()
#6 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Users))
#7 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-08-31 14:40:58 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in /var/www/html/app/Views/errors/html/error_exception.php:99
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', '/var/www/html/a...', 99, Array)
#1 /var/www/html/app/Views/errors/html/error_exception.php(99): print_r(Object(App\Controllers\Api\V1\Users), true)
#2 /var/www/html/vendor/codeigniter4/framework/system/Debug/Exceptions.php(278): include('/var/www/html/a...')
#3 /var/www/html/vendor/codeigniter4/framework/system/Debug/Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-08-31 14:40:58 --> Error connecting to the database: Access denied for user '****'@'172.29.0.4' (using ****: YES)
CRITICAL - 2021-08-31 14:40:58 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'172.29.0.4' (using ****: YES)
#0 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->initialize()
#1 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 /var/www/html/vendor/codeigniter4/framework/system/Model.php(197): CodeIgniter\Database\BaseBuilder->get()
#3 /var/www/html/vendor/codeigniter4/framework/system/BaseModel.php(603): CodeIgniter\Model->doFindAll(0, 0)
#4 /var/www/html/app/Controllers/Api/V1/Users.php(20): CodeIgniter\BaseModel->findAll()
#5 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): App\Controllers\Api\V1\Users->index()
#6 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Users))
#7 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-08-31 14:40:58 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in /var/www/html/app/Views/errors/html/error_exception.php:99
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', '/var/www/html/a...', 99, Array)
#1 /var/www/html/app/Views/errors/html/error_exception.php(99): print_r(Object(App\Controllers\Api\V1\Users), true)
#2 /var/www/html/vendor/codeigniter4/framework/system/Debug/Exceptions.php(278): include('/var/www/html/a...')
#3 /var/www/html/vendor/codeigniter4/framework/system/Debug/Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-08-31 14:42:20 --> Error connecting to the database: Access denied for user '****'@'172.29.0.4' (using ****: YES)
CRITICAL - 2021-08-31 14:42:20 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'172.29.0.4' (using ****: YES)
#0 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->initialize()
#1 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 /var/www/html/vendor/codeigniter4/framework/system/Model.php(197): CodeIgniter\Database\BaseBuilder->get()
#3 /var/www/html/vendor/codeigniter4/framework/system/BaseModel.php(603): CodeIgniter\Model->doFindAll(0, 0)
#4 /var/www/html/app/Controllers/Api/V1/Users.php(20): CodeIgniter\BaseModel->findAll()
#5 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): App\Controllers\Api\V1\Users->index()
#6 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Users))
#7 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-08-31 14:42:20 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in /var/www/html/app/Views/errors/html/error_exception.php:99
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', '/var/www/html/a...', 99, Array)
#1 /var/www/html/app/Views/errors/html/error_exception.php(99): print_r(Object(App\Controllers\Api\V1\Users), true)
#2 /var/www/html/vendor/codeigniter4/framework/system/Debug/Exceptions.php(278): include('/var/www/html/a...')
#3 /var/www/html/vendor/codeigniter4/framework/system/Debug/Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-08-31 14:42:21 --> Error connecting to the database: Access denied for user '****'@'172.29.0.4' (using ****: YES)
CRITICAL - 2021-08-31 14:42:21 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'172.29.0.4' (using ****: YES)
#0 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->initialize()
#1 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 /var/www/html/vendor/codeigniter4/framework/system/Model.php(197): CodeIgniter\Database\BaseBuilder->get()
#3 /var/www/html/vendor/codeigniter4/framework/system/BaseModel.php(603): CodeIgniter\Model->doFindAll(0, 0)
#4 /var/www/html/app/Controllers/Api/V1/Users.php(20): CodeIgniter\BaseModel->findAll()
#5 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): App\Controllers\Api\V1\Users->index()
#6 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Users))
#7 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-08-31 14:42:21 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in /var/www/html/app/Views/errors/html/error_exception.php:99
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', '/var/www/html/a...', 99, Array)
#1 /var/www/html/app/Views/errors/html/error_exception.php(99): print_r(Object(App\Controllers\Api\V1\Users), true)
#2 /var/www/html/vendor/codeigniter4/framework/system/Debug/Exceptions.php(278): include('/var/www/html/a...')
#3 /var/www/html/vendor/codeigniter4/framework/system/Debug/Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-08-31 14:42:21 --> Error connecting to the database: Access denied for user '****'@'172.29.0.4' (using ****: YES)
CRITICAL - 2021-08-31 14:42:21 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'172.29.0.4' (using ****: YES)
#0 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->initialize()
#1 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 /var/www/html/vendor/codeigniter4/framework/system/Model.php(197): CodeIgniter\Database\BaseBuilder->get()
#3 /var/www/html/vendor/codeigniter4/framework/system/BaseModel.php(603): CodeIgniter\Model->doFindAll(0, 0)
#4 /var/www/html/app/Controllers/Api/V1/Users.php(20): CodeIgniter\BaseModel->findAll()
#5 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): App\Controllers\Api\V1\Users->index()
#6 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Users))
#7 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-08-31 14:42:21 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in /var/www/html/app/Views/errors/html/error_exception.php:99
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', '/var/www/html/a...', 99, Array)
#1 /var/www/html/app/Views/errors/html/error_exception.php(99): print_r(Object(App\Controllers\Api\V1\Users), true)
#2 /var/www/html/vendor/codeigniter4/framework/system/Debug/Exceptions.php(278): include('/var/www/html/a...')
#3 /var/www/html/vendor/codeigniter4/framework/system/Debug/Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-08-31 14:42:21 --> Error connecting to the database: Access denied for user '****'@'172.29.0.4' (using ****: YES)
CRITICAL - 2021-08-31 14:42:21 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'172.29.0.4' (using ****: YES)
#0 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->initialize()
#1 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 /var/www/html/vendor/codeigniter4/framework/system/Model.php(197): CodeIgniter\Database\BaseBuilder->get()
#3 /var/www/html/vendor/codeigniter4/framework/system/BaseModel.php(603): CodeIgniter\Model->doFindAll(0, 0)
#4 /var/www/html/app/Controllers/Api/V1/Users.php(20): CodeIgniter\BaseModel->findAll()
#5 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): App\Controllers\Api\V1\Users->index()
#6 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Users))
#7 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-08-31 14:42:21 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in /var/www/html/app/Views/errors/html/error_exception.php:99
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', '/var/www/html/a...', 99, Array)
#1 /var/www/html/app/Views/errors/html/error_exception.php(99): print_r(Object(App\Controllers\Api\V1\Users), true)
#2 /var/www/html/vendor/codeigniter4/framework/system/Debug/Exceptions.php(278): include('/var/www/html/a...')
#3 /var/www/html/vendor/codeigniter4/framework/system/Debug/Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-08-31 14:42:21 --> Error connecting to the database: Access denied for user '****'@'172.29.0.4' (using ****: YES)
CRITICAL - 2021-08-31 14:42:21 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'172.29.0.4' (using ****: YES)
#0 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->initialize()
#1 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 /var/www/html/vendor/codeigniter4/framework/system/Model.php(197): CodeIgniter\Database\BaseBuilder->get()
#3 /var/www/html/vendor/codeigniter4/framework/system/BaseModel.php(603): CodeIgniter\Model->doFindAll(0, 0)
#4 /var/www/html/app/Controllers/Api/V1/Users.php(20): CodeIgniter\BaseModel->findAll()
#5 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): App\Controllers\Api\V1\Users->index()
#6 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Users))
#7 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-08-31 14:42:21 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in /var/www/html/app/Views/errors/html/error_exception.php:99
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', '/var/www/html/a...', 99, Array)
#1 /var/www/html/app/Views/errors/html/error_exception.php(99): print_r(Object(App\Controllers\Api\V1\Users), true)
#2 /var/www/html/vendor/codeigniter4/framework/system/Debug/Exceptions.php(278): include('/var/www/html/a...')
#3 /var/www/html/vendor/codeigniter4/framework/system/Debug/Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-08-31 14:42:22 --> Error connecting to the database: Access denied for user '****'@'172.29.0.4' (using ****: YES)
CRITICAL - 2021-08-31 14:42:22 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'172.29.0.4' (using ****: YES)
#0 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->initialize()
#1 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 /var/www/html/vendor/codeigniter4/framework/system/Model.php(197): CodeIgniter\Database\BaseBuilder->get()
#3 /var/www/html/vendor/codeigniter4/framework/system/BaseModel.php(603): CodeIgniter\Model->doFindAll(0, 0)
#4 /var/www/html/app/Controllers/Api/V1/Users.php(20): CodeIgniter\BaseModel->findAll()
#5 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): App\Controllers\Api\V1\Users->index()
#6 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Users))
#7 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-08-31 14:42:22 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in /var/www/html/app/Views/errors/html/error_exception.php:99
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', '/var/www/html/a...', 99, Array)
#1 /var/www/html/app/Views/errors/html/error_exception.php(99): print_r(Object(App\Controllers\Api\V1\Users), true)
#2 /var/www/html/vendor/codeigniter4/framework/system/Debug/Exceptions.php(278): include('/var/www/html/a...')
#3 /var/www/html/vendor/codeigniter4/framework/system/Debug/Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-08-31 14:43:47 --> Error connecting to the database: Connection refused
CRITICAL - 2021-08-31 14:43:47 --> Unable to connect to the database.
Main connection [MySQLi]: Connection refused
#0 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->initialize()
#1 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 /var/www/html/vendor/codeigniter4/framework/system/Model.php(197): CodeIgniter\Database\BaseBuilder->get()
#3 /var/www/html/vendor/codeigniter4/framework/system/BaseModel.php(603): CodeIgniter\Model->doFindAll(0, 0)
#4 /var/www/html/app/Controllers/Api/V1/Users.php(20): CodeIgniter\BaseModel->findAll()
#5 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): App\Controllers\Api\V1\Users->index()
#6 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Users))
#7 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-08-31 14:43:47 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in /var/www/html/app/Views/errors/html/error_exception.php:99
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', '/var/www/html/a...', 99, Array)
#1 /var/www/html/app/Views/errors/html/error_exception.php(99): print_r(Object(App\Controllers\Api\V1\Users), true)
#2 /var/www/html/vendor/codeigniter4/framework/system/Debug/Exceptions.php(278): include('/var/www/html/a...')
#3 /var/www/html/vendor/codeigniter4/framework/system/Debug/Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-08-31 14:47:12 --> Error connecting to the database: Connection refused
CRITICAL - 2021-08-31 14:47:12 --> Unable to connect to the database.
Main connection [MySQLi]: Connection refused
#0 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->initialize()
#1 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 /var/www/html/vendor/codeigniter4/framework/system/Model.php(197): CodeIgniter\Database\BaseBuilder->get()
#3 /var/www/html/vendor/codeigniter4/framework/system/BaseModel.php(603): CodeIgniter\Model->doFindAll(0, 0)
#4 /var/www/html/app/Controllers/Api/V1/Users.php(20): CodeIgniter\BaseModel->findAll()
#5 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): App\Controllers\Api\V1\Users->index()
#6 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Users))
#7 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-08-31 14:47:12 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in /var/www/html/app/Views/errors/html/error_exception.php:99
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', '/var/www/html/a...', 99, Array)
#1 /var/www/html/app/Views/errors/html/error_exception.php(99): print_r(Object(App\Controllers\Api\V1\Users), true)
#2 /var/www/html/vendor/codeigniter4/framework/system/Debug/Exceptions.php(278): include('/var/www/html/a...')
#3 /var/www/html/vendor/codeigniter4/framework/system/Debug/Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-08-31 14:47:14 --> Error connecting to the database: Connection refused
CRITICAL - 2021-08-31 14:47:14 --> Unable to connect to the database.
Main connection [MySQLi]: Connection refused
#0 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->initialize()
#1 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 /var/www/html/vendor/codeigniter4/framework/system/Model.php(197): CodeIgniter\Database\BaseBuilder->get()
#3 /var/www/html/vendor/codeigniter4/framework/system/BaseModel.php(603): CodeIgniter\Model->doFindAll(0, 0)
#4 /var/www/html/app/Controllers/Api/V1/Users.php(20): CodeIgniter\BaseModel->findAll()
#5 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): App\Controllers\Api\V1\Users->index()
#6 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Users))
#7 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-08-31 14:47:14 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in /var/www/html/app/Views/errors/html/error_exception.php:99
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', '/var/www/html/a...', 99, Array)
#1 /var/www/html/app/Views/errors/html/error_exception.php(99): print_r(Object(App\Controllers\Api\V1\Users), true)
#2 /var/www/html/vendor/codeigniter4/framework/system/Debug/Exceptions.php(278): include('/var/www/html/a...')
#3 /var/www/html/vendor/codeigniter4/framework/system/Debug/Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-08-31 14:47:26 --> Table 'database.users' doesn't exist
CRITICAL - 2021-08-31 14:47:26 --> Table 'database.users' doesn't exist
#0 /var/www/html/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(329): mysqli->query('SELECT *\nFROM `...')
#1 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 /var/www/html/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /var/www/html/vendor/codeigniter4/framework/system/Model.php(228): CodeIgniter\Database\BaseBuilder->get()
#5 /var/www/html/vendor/codeigniter4/framework/system/BaseModel.php(644): CodeIgniter\Model->doFirst()
#6 /var/www/html/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(156): CodeIgniter\BaseModel->first()
#7 /var/www/html/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(20): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#8 /var/www/html/vendor/myth/auth/src/Controllers/AuthController.php(88): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#9 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): Myth\Auth\Controllers\AuthController->attemptLogin()
#10 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2021-08-31 14:57:27 --> Undefined offset: 1
#0 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/NothingPersonalValidator.php(90): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined offse...', '/var/www/html/v...', 90, Array)
#1 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/NothingPersonalValidator.php(39): Myth\Auth\Authentication\Passwords\NothingPersonalValidator->isNotPersonal('147eueuss', Object(Myth\Auth\Entities\User))
#2 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/PasswordValidator.php(55): Myth\Auth\Authentication\Passwords\NothingPersonalValidator->check('147eueuss', Object(Myth\Auth\Entities\User))
#3 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/ValidationRules.php(45): Myth\Auth\Authentication\Passwords\PasswordValidator->check('147eueuss', Object(Myth\Auth\Entities\User))
#4 /var/www/html/vendor/codeigniter4/framework/system/Validation/Validation.php(312): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password('147eueuss', NULL)
#5 /var/www/html/vendor/codeigniter4/framework/system/Validation/Validation.php(159): CodeIgniter\Validation\Validation->processRules('password', 'password', '147eueuss', Array, Array)
#6 /var/www/html/vendor/codeigniter4/framework/system/Controller.php(183): CodeIgniter\Validation\Validation->run()
#7 /var/www/html/app/Controllers/Api/V1/Users.php(91): CodeIgniter\Controller->validate(Array)
#8 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): App\Controllers\Api\V1\Users->create()
#9 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Users))
#10 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2021-08-31 15:17:22 --> Undefined offset: 1
#0 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/NothingPersonalValidator.php(90): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined offse...', '/var/www/html/v...', 90, Array)
#1 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/NothingPersonalValidator.php(39): Myth\Auth\Authentication\Passwords\NothingPersonalValidator->isNotPersonal('147eueuss', Object(Myth\Auth\Entities\User))
#2 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/PasswordValidator.php(55): Myth\Auth\Authentication\Passwords\NothingPersonalValidator->check('147eueuss', Object(Myth\Auth\Entities\User))
#3 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/ValidationRules.php(45): Myth\Auth\Authentication\Passwords\PasswordValidator->check('147eueuss', Object(Myth\Auth\Entities\User))
#4 /var/www/html/vendor/codeigniter4/framework/system/Validation/Validation.php(312): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password('147eueuss', NULL)
#5 /var/www/html/vendor/codeigniter4/framework/system/Validation/Validation.php(159): CodeIgniter\Validation\Validation->processRules('password', 'password', '147eueuss', Array, Array)
#6 /var/www/html/vendor/codeigniter4/framework/system/Controller.php(183): CodeIgniter\Validation\Validation->run()
#7 /var/www/html/app/Controllers/Api/V1/Users.php(91): CodeIgniter\Controller->validate(Array)
#8 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): App\Controllers\Api\V1\Users->create()
#9 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Users))
#10 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2021-08-31 15:21:22 --> Undefined offset: 1
#0 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/NothingPersonalValidator.php(90): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined offse...', '/var/www/html/v...', 90, Array)
#1 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/NothingPersonalValidator.php(39): Myth\Auth\Authentication\Passwords\NothingPersonalValidator->isNotPersonal('147eueuss', Object(Myth\Auth\Entities\User))
#2 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/PasswordValidator.php(55): Myth\Auth\Authentication\Passwords\NothingPersonalValidator->check('147eueuss', Object(Myth\Auth\Entities\User))
#3 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/ValidationRules.php(45): Myth\Auth\Authentication\Passwords\PasswordValidator->check('147eueuss', Object(Myth\Auth\Entities\User))
#4 /var/www/html/vendor/codeigniter4/framework/system/Validation/Validation.php(312): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password('147eueuss', NULL)
#5 /var/www/html/vendor/codeigniter4/framework/system/Validation/Validation.php(159): CodeIgniter\Validation\Validation->processRules('password', 'password', '147eueuss', Array, Array)
#6 /var/www/html/vendor/codeigniter4/framework/system/Controller.php(183): CodeIgniter\Validation\Validation->run()
#7 /var/www/html/app/Controllers/Api/V1/Users.php(91): CodeIgniter\Controller->validate(Array)
#8 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): App\Controllers\Api\V1\Users->create()
#9 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Users))
#10 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2021-08-31 15:24:40 --> Undefined offset: 1
#0 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/NothingPersonalValidator.php(90): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined offse...', '/var/www/html/v...', 90, Array)
#1 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/NothingPersonalValidator.php(39): Myth\Auth\Authentication\Passwords\NothingPersonalValidator->isNotPersonal('147eueuss', Object(Myth\Auth\Entities\User))
#2 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/PasswordValidator.php(55): Myth\Auth\Authentication\Passwords\NothingPersonalValidator->check('147eueuss', Object(Myth\Auth\Entities\User))
#3 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/ValidationRules.php(45): Myth\Auth\Authentication\Passwords\PasswordValidator->check('147eueuss', Object(Myth\Auth\Entities\User))
#4 /var/www/html/vendor/codeigniter4/framework/system/Validation/Validation.php(312): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password('147eueuss', NULL)
#5 /var/www/html/vendor/codeigniter4/framework/system/Validation/Validation.php(159): CodeIgniter\Validation\Validation->processRules('password', 'password', '147eueuss', Array, Array)
#6 /var/www/html/vendor/codeigniter4/framework/system/Controller.php(183): CodeIgniter\Validation\Validation->run()
#7 /var/www/html/app/Controllers/Api/V1/Users.php(91): CodeIgniter\Controller->validate(Array)
#8 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): App\Controllers\Api\V1\Users->create()
#9 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Users))
#10 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2021-08-31 15:29:06 --> Undefined offset: 1
#0 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/NothingPersonalValidator.php(90): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined offse...', '/var/www/html/v...', 90, Array)
#1 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/NothingPersonalValidator.php(39): Myth\Auth\Authentication\Passwords\NothingPersonalValidator->isNotPersonal('147eueuss', Object(Myth\Auth\Entities\User))
#2 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/PasswordValidator.php(55): Myth\Auth\Authentication\Passwords\NothingPersonalValidator->check('147eueuss', Object(Myth\Auth\Entities\User))
#3 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/ValidationRules.php(45): Myth\Auth\Authentication\Passwords\PasswordValidator->check('147eueuss', Object(Myth\Auth\Entities\User))
#4 /var/www/html/vendor/codeigniter4/framework/system/Validation/Validation.php(312): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password('147eueuss', NULL)
#5 /var/www/html/vendor/codeigniter4/framework/system/Validation/Validation.php(159): CodeIgniter\Validation\Validation->processRules('password', 'password', '147eueuss', Array, Array)
#6 /var/www/html/vendor/codeigniter4/framework/system/Controller.php(183): CodeIgniter\Validation\Validation->run()
#7 /var/www/html/app/Controllers/Api/V1/Users.php(91): CodeIgniter\Controller->validate(Array)
#8 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): App\Controllers\Api\V1\Users->create()
#9 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Users))
#10 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2021-08-31 15:29:35 --> Argument 1 passed to CodeIgniter\HTTP\IncomingRequest::getJSON() must be of the type bool, array given, called in /var/www/html/vendor/myth/auth/src/Authentication/Passwords/ValidationRules.php on line 70
#0 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/ValidationRules.php(70): CodeIgniter\HTTP\IncomingRequest->getJSON(Array)
#1 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/ValidationRules.php(42): Myth\Auth\Authentication\Passwords\ValidationRules->buildUserFromRequest()
#2 /var/www/html/vendor/codeigniter4/framework/system/Validation/Validation.php(312): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password('147eueuss', NULL)
#3 /var/www/html/vendor/codeigniter4/framework/system/Validation/Validation.php(159): CodeIgniter\Validation\Validation->processRules('password', 'password', '147eueuss', Array, Array)
#4 /var/www/html/vendor/codeigniter4/framework/system/Controller.php(183): CodeIgniter\Validation\Validation->run()
#5 /var/www/html/app/Controllers/Api/V1/Users.php(91): CodeIgniter\Controller->validate(Array)
#6 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): App\Controllers\Api\V1\Users->create()
#7 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Users))
#8 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-08-31 15:30:50 --> array_filter() expects parameter 1 to be array, object given
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'array_filter() ...', '/var/www/html/v...', 72, Array)
#1 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/ValidationRules.php(72): array_filter(Object(stdClass))
#2 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/ValidationRules.php(42): Myth\Auth\Authentication\Passwords\ValidationRules->buildUserFromRequest()
#3 /var/www/html/vendor/codeigniter4/framework/system/Validation/Validation.php(312): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password('147eueuss', NULL)
#4 /var/www/html/vendor/codeigniter4/framework/system/Validation/Validation.php(159): CodeIgniter\Validation\Validation->processRules('password', 'password', '147eueuss', Array, Array)
#5 /var/www/html/vendor/codeigniter4/framework/system/Controller.php(183): CodeIgniter\Validation\Validation->run()
#6 /var/www/html/app/Controllers/Api/V1/Users.php(91): CodeIgniter\Controller->validate(Array)
#7 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): App\Controllers\Api\V1\Users->create()
#8 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Users))
#9 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-08-31 15:37:20 --> Argument 1 passed to CodeIgniter\Entity\Entity::__construct() must be of the type array or null, object given, called in /var/www/html/vendor/myth/auth/src/Authentication/Passwords/ValidationRules.php on line 74
#0 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/ValidationRules.php(74): CodeIgniter\Entity\Entity->__construct(Object(stdClass))
#1 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/ValidationRules.php(42): Myth\Auth\Authentication\Passwords\ValidationRules->buildUserFromRequest()
#2 /var/www/html/vendor/codeigniter4/framework/system/Validation/Validation.php(312): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password('147eueuss', NULL)
#3 /var/www/html/vendor/codeigniter4/framework/system/Validation/Validation.php(159): CodeIgniter\Validation\Validation->processRules('password', 'password', '147eueuss', Array, Array)
#4 /var/www/html/vendor/codeigniter4/framework/system/Controller.php(183): CodeIgniter\Validation\Validation->run()
#5 /var/www/html/app/Controllers/Api/V1/Users.php(91): CodeIgniter\Controller->validate(Array)
#6 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): App\Controllers\Api\V1\Users->create()
#7 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Users))
#8 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-08-31 15:41:17 --> json_decode() expects parameter 1 to be string, object given
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'json_decode() e...', '/var/www/html/v...', 70, Array)
#1 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/ValidationRules.php(70): json_decode(Object(stdClass))
#2 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/ValidationRules.php(42): Myth\Auth\Authentication\Passwords\ValidationRules->buildUserFromRequest()
#3 /var/www/html/vendor/codeigniter4/framework/system/Validation/Validation.php(312): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password('147eueuss', NULL)
#4 /var/www/html/vendor/codeigniter4/framework/system/Validation/Validation.php(159): CodeIgniter\Validation\Validation->processRules('password', 'password', '147eueuss', Array, Array)
#5 /var/www/html/vendor/codeigniter4/framework/system/Controller.php(183): CodeIgniter\Validation\Validation->run()
#6 /var/www/html/app/Controllers/Api/V1/Users.php(91): CodeIgniter\Controller->validate(Array)
#7 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): App\Controllers\Api\V1\Users->create()
#8 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Users))
#9 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-08-31 15:48:44 --> Undefined offset: 1
#0 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/NothingPersonalValidator.php(90): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined offse...', '/var/www/html/v...', 90, Array)
#1 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/NothingPersonalValidator.php(39): Myth\Auth\Authentication\Passwords\NothingPersonalValidator->isNotPersonal('147eueuss', Object(Myth\Auth\Entities\User))
#2 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/PasswordValidator.php(55): Myth\Auth\Authentication\Passwords\NothingPersonalValidator->check('147eueuss', Object(Myth\Auth\Entities\User))
#3 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/ValidationRules.php(45): Myth\Auth\Authentication\Passwords\PasswordValidator->check('147eueuss', Object(Myth\Auth\Entities\User))
#4 /var/www/html/vendor/codeigniter4/framework/system/Validation/Validation.php(312): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password('147eueuss', NULL)
#5 /var/www/html/vendor/codeigniter4/framework/system/Validation/Validation.php(159): CodeIgniter\Validation\Validation->processRules('password', 'password', '147eueuss', Array, Array)
#6 /var/www/html/vendor/codeigniter4/framework/system/Controller.php(183): CodeIgniter\Validation\Validation->run()
#7 /var/www/html/app/Controllers/Api/V1/Users.php(91): CodeIgniter\Controller->validate(Array)
#8 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): App\Controllers\Api\V1\Users->create()
#9 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Users))
#10 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2021-08-31 15:48:45 --> Undefined offset: 1
#0 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/NothingPersonalValidator.php(90): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined offse...', '/var/www/html/v...', 90, Array)
#1 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/NothingPersonalValidator.php(39): Myth\Auth\Authentication\Passwords\NothingPersonalValidator->isNotPersonal('147eueuss', Object(Myth\Auth\Entities\User))
#2 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/PasswordValidator.php(55): Myth\Auth\Authentication\Passwords\NothingPersonalValidator->check('147eueuss', Object(Myth\Auth\Entities\User))
#3 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/ValidationRules.php(45): Myth\Auth\Authentication\Passwords\PasswordValidator->check('147eueuss', Object(Myth\Auth\Entities\User))
#4 /var/www/html/vendor/codeigniter4/framework/system/Validation/Validation.php(312): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password('147eueuss', NULL)
#5 /var/www/html/vendor/codeigniter4/framework/system/Validation/Validation.php(159): CodeIgniter\Validation\Validation->processRules('password', 'password', '147eueuss', Array, Array)
#6 /var/www/html/vendor/codeigniter4/framework/system/Controller.php(183): CodeIgniter\Validation\Validation->run()
#7 /var/www/html/app/Controllers/Api/V1/Users.php(91): CodeIgniter\Controller->validate(Array)
#8 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): App\Controllers\Api\V1\Users->create()
#9 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Users))
#10 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2021-08-31 15:57:05 --> Undefined offset: 1
#0 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/NothingPersonalValidator.php(90): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined offse...', '/var/www/html/v...', 90, Array)
#1 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/NothingPersonalValidator.php(39): Myth\Auth\Authentication\Passwords\NothingPersonalValidator->isNotPersonal('147eueuss', Object(Myth\Auth\Entities\User))
#2 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/PasswordValidator.php(55): Myth\Auth\Authentication\Passwords\NothingPersonalValidator->check('147eueuss', Object(Myth\Auth\Entities\User))
#3 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/ValidationRules.php(45): Myth\Auth\Authentication\Passwords\PasswordValidator->check('147eueuss', Object(Myth\Auth\Entities\User))
#4 /var/www/html/vendor/codeigniter4/framework/system/Validation/Validation.php(312): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password('147eueuss', NULL)
#5 /var/www/html/vendor/codeigniter4/framework/system/Validation/Validation.php(159): CodeIgniter\Validation\Validation->processRules('password', 'password', '147eueuss', Array, Array)
#6 /var/www/html/vendor/codeigniter4/framework/system/Controller.php(183): CodeIgniter\Validation\Validation->run()
#7 /var/www/html/app/Controllers/Api/V1/Users.php(91): CodeIgniter\Controller->validate(Array)
#8 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): App\Controllers\Api\V1\Users->create()
#9 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Users))
#10 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2021-08-31 15:57:10 --> Undefined offset: 1
#0 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/NothingPersonalValidator.php(90): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined offse...', '/var/www/html/v...', 90, Array)
#1 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/NothingPersonalValidator.php(39): Myth\Auth\Authentication\Passwords\NothingPersonalValidator->isNotPersonal('147eueuss', Object(Myth\Auth\Entities\User))
#2 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/PasswordValidator.php(55): Myth\Auth\Authentication\Passwords\NothingPersonalValidator->check('147eueuss', Object(Myth\Auth\Entities\User))
#3 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/ValidationRules.php(45): Myth\Auth\Authentication\Passwords\PasswordValidator->check('147eueuss', Object(Myth\Auth\Entities\User))
#4 /var/www/html/vendor/codeigniter4/framework/system/Validation/Validation.php(312): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password('147eueuss', NULL)
#5 /var/www/html/vendor/codeigniter4/framework/system/Validation/Validation.php(159): CodeIgniter\Validation\Validation->processRules('password', 'password', '147eueuss', Array, Array)
#6 /var/www/html/vendor/codeigniter4/framework/system/Controller.php(183): CodeIgniter\Validation\Validation->run()
#7 /var/www/html/app/Controllers/Api/V1/Users.php(91): CodeIgniter\Controller->validate(Array)
#8 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): App\Controllers\Api\V1\Users->create()
#9 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Users))
#10 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2021-08-31 15:57:15 --> Undefined offset: 1
#0 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/NothingPersonalValidator.php(90): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined offse...', '/var/www/html/v...', 90, Array)
#1 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/NothingPersonalValidator.php(39): Myth\Auth\Authentication\Passwords\NothingPersonalValidator->isNotPersonal('147eueuss', Object(Myth\Auth\Entities\User))
#2 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/PasswordValidator.php(55): Myth\Auth\Authentication\Passwords\NothingPersonalValidator->check('147eueuss', Object(Myth\Auth\Entities\User))
#3 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/ValidationRules.php(45): Myth\Auth\Authentication\Passwords\PasswordValidator->check('147eueuss', Object(Myth\Auth\Entities\User))
#4 /var/www/html/vendor/codeigniter4/framework/system/Validation/Validation.php(312): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password('147eueuss', NULL)
#5 /var/www/html/vendor/codeigniter4/framework/system/Validation/Validation.php(159): CodeIgniter\Validation\Validation->processRules('password', 'password', '147eueuss', Array, Array)
#6 /var/www/html/vendor/codeigniter4/framework/system/Controller.php(183): CodeIgniter\Validation\Validation->run()
#7 /var/www/html/app/Controllers/Api/V1/Users.php(91): CodeIgniter\Controller->validate(Array)
#8 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): App\Controllers\Api\V1\Users->create()
#9 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Users))
#10 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2021-08-31 15:59:02 --> json_decode() expects parameter 1 to be string, object given
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'json_decode() e...', '/var/www/html/v...', 73, Array)
#1 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/ValidationRules.php(73): json_decode(Object(stdClass), true)
#2 /var/www/html/vendor/myth/auth/src/Authentication/Passwords/ValidationRules.php(42): Myth\Auth\Authentication\Passwords\ValidationRules->buildUserFromRequest()
#3 /var/www/html/vendor/codeigniter4/framework/system/Validation/Validation.php(312): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password('147eueuss', NULL)
#4 /var/www/html/vendor/codeigniter4/framework/system/Validation/Validation.php(159): CodeIgniter\Validation\Validation->processRules('password', 'password', '147eueuss', Array, Array)
#5 /var/www/html/vendor/codeigniter4/framework/system/Controller.php(183): CodeIgniter\Validation\Validation->run()
#6 /var/www/html/app/Controllers/Api/V1/Users.php(91): CodeIgniter\Controller->validate(Array)
#7 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): App\Controllers\Api\V1\Users->create()
#8 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Users))
#9 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-08-31 16:00:32 --> syntax error, unexpected ')'
#0 /var/www/html/vendor/codeigniter4/framework/system/Autoloader/Autoloader.php(273): CodeIgniter\Autoloader\Autoloader->includeFile('/var/www/html/v...')
#1 /var/www/html/vendor/codeigniter4/framework/system/Autoloader/Autoloader.php(247): CodeIgniter\Autoloader\Autoloader->loadInNamespace('Myth\\Auth\\Authe...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('Myth\\Auth\\Authe...')
#3 /var/www/html/vendor/codeigniter4/framework/system/Validation/Validation.php(576): spl_autoload_call('Myth\\Auth\\Authe...')
#4 /var/www/html/vendor/codeigniter4/framework/system/Validation/Validation.php(118): CodeIgniter\Validation\Validation->loadRuleSets()
#5 /var/www/html/vendor/codeigniter4/framework/system/Controller.php(183): CodeIgniter\Validation\Validation->run()
#6 /var/www/html/app/Controllers/Api/V1/Users.php(91): CodeIgniter\Controller->validate(Array)
#7 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): App\Controllers\Api\V1\Users->create()
#8 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Users))
#9 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-08-31 16:25:38 --> Undefined property: App\Controllers\Api\V1\Users::$config
#0 /var/www/html/app/Controllers/Api/V1/Users.php(100): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', '/var/www/html/a...', 100, Array)
#1 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): App\Controllers\Api\V1\Users->create()
#2 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Users))
#3 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-08-31 16:26:31 --> array_filter() expects parameter 2 to be a valid callback, array must have exactly two members
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'array_filter() ...', '/var/www/html/a...', 102, Array)
#1 /var/www/html/app/Controllers/Api/V1/Users.php(102): array_filter(Array, Array)
#2 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): App\Controllers\Api\V1\Users->create()
#3 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Users))
#4 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-08-31 16:49:50 --> array_filter() expects parameter 2 to be a valid callback, array must have exactly two members
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'array_filter() ...', '/var/www/html/a...', 102, Array)
#1 /var/www/html/app/Controllers/Api/V1/Users.php(102): array_filter(Array, Array)
#2 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): App\Controllers\Api\V1\Users->create()
#3 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Users))
#4 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-08-31 16:51:23 --> Undefined variable: files
#0 /var/www/html/app/Controllers/Api/V1/Users.php(104): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', '/var/www/html/a...', 104, Array)
#1 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): App\Controllers\Api\V1\Users->create()
#2 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Users))
#3 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-08-31 16:55:42 --> Constant expression contains invalid operations
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-08-31 16:56:06 --> syntax error, unexpected 'Auth' (T_STRING), expecting ',' or ';'
#0 /var/www/html/vendor/codeigniter4/framework/system/Autoloader/Autoloader.php(273): CodeIgniter\Autoloader\Autoloader->includeFile('/var/www/html/v...')
#1 /var/www/html/vendor/codeigniter4/framework/system/Autoloader/Autoloader.php(247): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(885): class_exists('\\App\\Controller...', true)
#5 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(421): CodeIgniter\CodeIgniter->startController()
#6 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-08-31 16:56:20 --> Trying to get property 'requireActivation' of non-object
#0 /var/www/html/app/Controllers/Api/V1/Users.php(106): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', '/var/www/html/a...', 106, Array)
#1 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(928): App\Controllers\Api\V1\Users->create()
#2 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\V1\Users))
#3 /var/www/html/vendor/codeigniter4/framework/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /var/www/html/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
